# Patches for the 89-question file (batu recollections). Keyed by the file's own "id".
# Every kept item gets a topic and a real explanation (the source only had a template sentence).
# q/o/a only appear when the stem, options or key changed. note = provenance shown under the explanation.

A = {
40: dict(topic='ana', q='Yang termasuk baku primer untuk titrasi redoks adalah…', a=[4, 2],
  e='K2Cr2O7 bisa diperoleh dalam keadaan sangat murni, stabil, dan tidak higroskopis, jadi larutannya langsung diketahui konsentrasinya tanpa perlu distandardisasi. K biftalat dan Na2CO3 adalah baku primer titrasi asam-basa, sedangkan NaCl dipakai di argentometri.',
  note='Kunci batu: K2Cr2O7. KIO3 juga baku primer redoks (dipakai di iodometri), jadi pilihan itu ikut dihitung benar.'),
27: dict(topic='tek',
  e='Aplikasi adalah perangkat lunak yang dipasang di atas sistem operasi sebuah alat untuk menjalankan fungsi tertentu. Perangkat keras adalah komponen fisiknya, sedangkan sistem operasi adalah program dasar yang mengelola alat itu.'),
67: dict(topic='ana', q='Pada spektrofotometri diketahui absorbansi baku 0,8, konsentrasi baku 100 ppm, absorbansi sampel 0,2, dan faktor pengenceran 10 kali. Berapakah kadar sampel tersebut?',
  e='Bandingkan dengan larutan baku: C sampel = (A sampel / A baku) × C baku = (0,2 / 0,8) × 100 ppm = 25 ppm. Sampel tadi sudah diencerkan 10 kali, jadi kadar awalnya 25 × 10 = 250 ppm.'),
74: dict(topic='bio',
  q='Dalam pemeriksaan hiperlipidemia, terdapat partikel lipoprotein terbesar yang membawa trigliserida dari makanan menuju jaringan perifer. Jenis lipoprotein apakah itu?',
  o=['HDL', 'LDL', 'VLDL', 'Kilomikron'], a=[3],
  e='Kilomikron dibentuk di sel usus dari lemak makanan. Ukurannya paling besar dan densitasnya paling rendah, lalu ia membawa trigliserida eksogen lewat pembuluh limfe ke jaringan perifer. VLDL membawa trigliserida buatan hati, LDL membawa kolesterol ke jaringan, dan HDL mengangkut kolesterol kembali ke hati.',
  note='Teks soal di file asli terpotong dan sebagian masuk ke pilihan A. Kalimatnya dilengkapi, pilihan jawabannya tetap.'),
14: dict(topic='org', q='Reaksi antara asam salisilat dengan anhidrida asetat, dengan asam sulfat sebagai katalisator, menghasilkan asam asetilsalisilat. Reaksi apakah yang dimaksud?', o=['Oksidasi', 'Reduksi', 'Esterifikasi', 'Adisi', 'Eliminasi'],
  e='Gugus OH fenol pada asam salisilat bereaksi dengan anhidrida asetat membentuk gugus ester, sehingga terbentuk asam asetilsalisilat (aspirin). Reaksi pembentukan ester seperti ini disebut esterifikasi.',
  note='Di file asli pereaksinya tertulis etanol. Asam salisilat + etanol menghasilkan etil salisilat, bukan aspirin, jadi pereaksinya dibetulkan. Kuncinya tetap esterifikasi.'),
25: dict(topic='ling', q='Pekerja di pabrik kimia terpapar NO2 dan VOC. Senyawa apa yang terbentuk dari reaksi keduanya?',
  e='NO2 dan VOC yang terkena sinar matahari membentuk smog fotokimia dengan produk utama ozon dan peroksiasetil nitrat (PAN). PAN mengiritasi mata dan saluran napas. CFC, SO2, dan CO tidak terbentuk dari reaksi ini.'),
'NEW': dict(topic='bio', q='Saat terjadi distrofi otot, proses apa yang terganggu di dalam tubuh?',
  o=['Glikolisis glukosa', 'Glikogenesis', 'Glukoneogenesis', 'Beta-oksidasi', 'Siklus Krebs'],
  e='Distrofi otot berawal dari kelainan protein struktural serat otot, misalnya distrofin pada distrofi Duchenne. Serat otot yang terus rusak ikut terganggu metabolisme energinya, dan jalur yang disorot soal ini adalah glikolisis glukosa.',
  note='Kunci mengikuti batu. Soal ini tidak menjelaskan konteksnya, jadi pakai sebagai hafalan kunci.'),
47: dict(topic='min', q='Mineral ini penting untuk gigi dan tulang, berfungsi memperkuat gigi dan menjaga kepadatan tulang. Mineral apakah ini?',
  e='Fluor (F) masuk ke kristal hidroksiapatit dan membentuk fluorapatit yang lebih tahan asam, jadi enamel gigi lebih kuat. Fluor juga ikut menjaga kepadatan mineral tulang. Fosfor memang penyusun tulang, tapi fungsi memperkuat gigi paling khas milik fluor.'),
7: dict(topic='min', q='Mineral yang berfungsi dalam jantung dan pembuluh darah serta dalam kerja enzim xantin oksidase dan aldehida oksidase, yang jika berlebih akan mengakibatkan hiperurisemia, adalah…',
  e='Molibdenum (Mo) adalah kofaktor xantin oksidase, aldehida oksidase, dan sulfit oksidase. Xantin oksidase mengubah hipoksantin dan xantin menjadi asam urat, sehingga Mo berlebih dikaitkan dengan kadar asam urat tinggi (hiperurisemia).'),
77: dict(topic='min', q='Mineral ini termasuk ke dalam vitamin B12, dengan fungsi membentuk sel darah merah dan merawat saraf. Mineral apakah ini?',
  e='Kobalt (Co) adalah atom pusat kobalamin (vitamin B12). Vitamin B12 dibutuhkan untuk pembentukan eritrosit dan pemeliharaan mielin, jadi kekurangannya bisa menyebabkan anemia megaloblastik dan gangguan saraf.',
  note='Di file asli tertulis "protein B12". Yang dimaksud vitamin B12.'),
50: dict(topic='prot', q='Prekursor atau bahan dasar bagi tubuh untuk menyintesis hormon tiroid T3 dan T4 serta hormon katekolamin seperti epinefrin adalah…',
  e='Tirosin menjadi hormon tiroid lewat iodinasi di tiroglobulin, dan menjadi katekolamin (dopamin, norepinefrin, epinefrin) lewat L-DOPA. Triptofan adalah prekursor serotonin dan melatonin, histidin prekursor histamin, dan arginin prekursor NO.'),
10: dict(topic='bio', q='Komponen membran yang berfungsi menjaga fluiditas membran adalah…',
  e='Kolesterol menyisip di antara fosfolipid dan menahan fluiditas tetap stabil. Pada suhu tinggi ia membatasi gerak rantai asam lemak, pada suhu rendah ia mencegah rantai itu merapat sampai membeku.'),
21: dict(topic='bio', q='Senyawa yang dapat membantu mengatasi penggumpalan darah adalah…',
  e='Heparin adalah antikoagulan. Ia mengikat antitrombin III dan mempercepat kerjanya menonaktifkan trombin dan faktor Xa, sehingga bekuan tidak terbentuk. Fibrinogen justru bahan baku bekuan.'),
22: dict(topic='tek', q='Kanker adalah penyakit yang disebabkan oleh ketidakteraturan perjalanan hormon yang mengakibatkan tumbuhnya daging pada jaringan tubuh yang normal atau sering dikenal sebagai tumor ganas. Selain itu gejala ini juga dikenal sebagai neoplasma ganas dan sering kali ditandai dengan kelainan siklus sel yang khas. Apakah manfaat spesifik penggunaan teknologi kedokteran yang berkaitan dengan penyakit di atas?',
  a=[1, 2],
  e='Manfaat teknologi kedokteran di materi ini dibagi antara lain untuk pencegahan, diagnosis, terapi, monitoring, dan rehabilitasi. Untuk kanker, teknologi yang paling khas adalah alat terapi seperti radioterapi.',
  note='Kunci batu: terapi. Terapi dan pengobatan artinya sama, jadi dua-duanya dihitung benar. Kalimat pembuka soal mengikuti batu dan kurang tepat: kanker berawal dari mutasi genetik yang membuat sel tumbuh tak terkendali, bukan dari gangguan hormon.'),
8: dict(topic='min', q='Mineral yang berkontribusi dalam kerja insulin serta metabolisme lemak, glukosa, dan protein adalah…',
  e='Kromium (Cr) membantu kerja insulin dengan meningkatkan sensitivitas reseptornya, sehingga terlibat dalam metabolisme glukosa, lemak, dan protein.'),
55: dict(topic='bio',
  e='Glikokonjugat adalah karbohidrat yang terikat kovalen ke protein atau lipid: glikoprotein, proteoglikan, dan glikolipid. Di permukaan sel molekul ini menjadi reseptor sinyal, penanda imun (misalnya antigen golongan darah), dan tempat menempelnya toksin mikroba.'),
41: dict(topic='prot', q='Asam amino yang menjadi prekursor pembentukan NO adalah…',
  e='Enzim NO sintase mengubah L-arginin menjadi oksida nitrat (NO) dan sitrulin. NO bekerja sebagai vasodilator dan molekul sinyal.'),
73: dict(topic='ana', q='100 mg sampel asetosal (Mr = 180) dititrasi dengan NaOH 0,1 M dan membutuhkan 5 mL. Berapa kadar asetosal dalam sampel?',
  e='Asetosal asam monoprotik, jadi bereaksi 1 : 1 dengan NaOH. Mol NaOH = 0,1 M × 5 mL = 0,5 mmol, setara 0,5 mmol asetosal = 0,5 × 180 = 90 mg. Kadarnya 90/100 × 100% = 90%.'),
83: dict(topic='ling', q='Seorang pekerja bekerja di ruangan tertutup sehingga kekurangan O2 dan mengalami hipoksia. Apa penyebab terjadinya hal tersebut?',
  e='Di ruangan tertutup O2 terus terpakai, sementara CO2 dari napas menumpuk. CO2 yang tinggi di udara dan di alveolus menggeser tempat O2, sehingga tekanan parsial O2 di alveolus turun dan terjadi hipoksia.'),
68: dict(topic='ana', q='Uji sederhana untuk memeriksa keberadaan NAPZA melalui tes urin adalah…',
  e='KLT murah dan cepat, dan bisa memisahkan serta mengenali obat atau metabolitnya di urin dari nilai Rf. Karena itu KLT sering dipakai untuk skrining NAPZA. Titrimetri dan gravimetri adalah metode kuantitatif, bukan skrining.'),
84: dict(topic='fis', o=['Difusi (hukum Fick) mengikuti gradien', 'Osmosis melawan gradien', 'Difusi melawan gradien', 'Filtrasi', 'Transpor aktif'],
  e='O2 berpindah dari alveolus (PO2 sekitar 104 mmHg) ke darah kapiler (sekitar 40 mmHg) lewat difusi pasif menuruni gradien tekanan parsial. Lajunya mengikuti hukum Fick: makin besar luas permukaan dan beda tekanan, makin cepat; makin tebal membran, makin lambat.'),
15: dict(topic='bio', q='Mengapa PUFA dapat menyebabkan membran lebih cair?',
  o=['PUFA memiliki banyak ikatan rantai karbon sehingga ikatan menjadi lurus', 'PUFA memiliki banyak ikatan rangkap karbon sehingga rantainya berlekuk', 'Rantai karbon PUFA lurus karena tidak memiliki ikatan rangkap', 'PUFA memiliki satu ikatan rangkap sehingga rantainya lurus', 'Tidak ada pilihan lain yang sesuai'],
  e='Setiap ikatan rangkap cis membuat rantai asam lemak menekuk. Rantai yang bengkok tidak bisa tersusun rapat, interaksi antarrantai melemah, dan membran jadi lebih cair.'),
11: dict(topic='saraf', q='Jika terjadi cedera pada hamstring, gangguan yang paling terlihat adalah…',
  e='Hamstring melintasi dua sendi. Di panggul ia mengekstensikan paha, di lutut ia memfleksikan tungkai. Cedera hamstring paling terasa saat menekuk lutut dan meluruskan panggul.'),
98: dict(topic='ana', q='Analisis kimia kuantitatif yang menghitung kadar suatu senyawa atau obat dalam satuan gram disebut…',
  o=['Iodometri', 'Titrimetri', 'Gravimetri', 'Volumetri', 'Instrumental'],
  e='Gravimetri menentukan kadar dari massa. Zatnya biasanya diendapkan, dikeringkan, lalu ditimbang. Titrimetri atau volumetri mengukur volume titran, dan iodometri adalah salah satu jenis titrasi redoks.'),
43: dict(topic='prot', q='Asam amino yang bersifat sebagai pemecah heliks (helix breaker) adalah…',
  o=['Glisin', 'Prolin', 'Valin', 'Leusin', 'Alanin'],
  e='Rantai samping prolin membentuk cincin dengan nitrogen aminonya, sehingga sudut ikatannya kaku dan tidak ada H di nitrogen untuk ikatan hidrogen heliks. Akibatnya prolin memutus α-heliks. Glisin juga bisa mengganggu heliks, tapi alasannya karena terlalu fleksibel.'),
60: dict(topic='ling', q='Zat kimia pencemar lingkungan yang menyebabkan hujan asam adalah…',
  a=[0, 2],
  e='SO2 dari pembakaran bahan bakar fosil teroksidasi menjadi SO3, lalu bereaksi dengan air membentuk asam sulfat, penyebab utama hujan asam. NO2 juga menyebabkan hujan asam lewat asam nitrat.',
  note='Kunci batu: SO2. NO2 juga penyebab hujan asam dan soalnya tidak meminta penyebab utama, jadi dua-duanya dihitung benar.'),
1: dict(topic='bio', q='Jenis karbohidrat yang berperan sebagai antikoagulan, yaitu heteropolisakarida yang mengikat antitrombin III sehingga memblokir pembekuan darah secara efisien, adalah…',
  e='Heparin adalah glikosaminoglikan (heteropolisakarida bersulfat). Ikatannya dengan antitrombin III mempercepat inaktivasi trombin dan faktor Xa, jadi pembekuan darah terhambat.',
  note='Di file asli tertulis "koagulan", padahal fungsinya antikoagulan.'),
26: dict(topic='bio', q='Lipid ini memiliki kepala gliserol dan tiga ekor asam lemak. Termasuk senyawa lipid apakah ini?',
  o=['Lipid kompleks - trigliserida', 'Lipid sederhana - trigliserida', 'Lipid kompleks - fosfolipid', 'Lipid sederhana - fosfolipid', 'Tidak ada pilihan lain yang sesuai'],
  e='Trigliserida adalah ester gliserol dengan tiga asam lemak. Karena penyusunnya hanya asam lemak dan alkohol, ia masuk lipid sederhana. Fosfolipid termasuk lipid kompleks karena punya gugus fosfat, dan sering juga basa nitrogen.'),
56: dict(topic='bio', q='Nanopartikel berbasis polisakarida yang berfungsi untuk penargetan reseptor dan pengiriman obat tertarget adalah…',
  o=['Heparin', 'Dekstran', 'Kitosan', 'Alginat', 'Pati'],
  e='Dekstran adalah polisakarida glukosa bercabang yang mudah dimodifikasi dan dipasangi ligan, sehingga dipakai sebagai nanopartikel yang menargetkan reseptor dan mengantar obat ke sel sasaran. Contohnya tilmanocept, dekstran bermanosa yang menempel ke reseptor manosa makrofag.',
  note='Kunci mengikuti batu. Kitosan juga bisa dibuat nanopartikel, tapi di batu yang dipasangkan dengan penargetan reseptor adalah dekstran.'),
17: dict(topic='ab', q='Indikator fenolftalein mempunyai trayek pH pada kisaran…', o=['8,3-10', '7,45-8', '6-7,35', '4-5', '3-5'],
  e='Fenolftalein tidak berwarna di bawah pH sekitar 8,3 dan berubah merah muda sampai pH sekitar 10. Karena itu fenolftalein cocok untuk titrasi asam lemah dengan basa kuat, yang titik ekuivalennya di atas 7.',
  note='File 200 soal memakai kunci 7,5-8,8 untuk soal yang sama. Soalnya digabung dan memakai trayek standar di literatur, 8,3-10.'),
85: dict(topic='ab', q='100 mL larutan HCl 0,2 M dicampurkan dengan 200 mL larutan NH4OH 0,2 M (Kb = 2 × 10⁻⁵). Berapakah pH akhir larutan tersebut?',
  e='HCl 20 mmol bereaksi dengan NH4OH 40 mmol, tersisa NH4OH 20 mmol dan terbentuk NH4Cl 20 mmol. Campuran basa lemah dan garamnya adalah buffer basa: [OH⁻] = Kb × 20/20 = 2 × 10⁻⁵, pOH = 5 - log 2, jadi pH = 9 + log 2.'),
44: dict(topic='prot', q='Protein dilarutkan dalam buffer dengan pH di atas titik isoelektriknya (pH > pI), lalu dialiri arus listrik (elektroforesis). Apa yang terjadi pada protein tersebut?',
  e='Di atas pI, gugus yang masih membawa proton (terutama -NH3⁺) mulai melepasnya, sehingga muatan positif berkurang dan muatan bersih protein menjadi negatif. Protein lalu bergerak ke anoda (kutub positif). Di bawah pI protein bermuatan positif dan bergerak ke katoda, sedangkan tepat di pI protein diam.',
  note='Teks soal ini tidak tercatat di batu ("lupa detail soal"). Soalnya disusun ulang supaya cocok dengan pilihan dan kunci aslinya.'),
93: dict(topic='prot', q='Ikatan yang terbentuk antara gugus -SH dari dua residu sistein adalah…',
  e='Oksidasi dua gugus tiol (-SH) sistein membentuk ikatan disulfida (-S-S-), jembatan kovalen yang menstabilkan struktur tersier dan kuaterner protein, misalnya pada insulin dan keratin.'),
58: dict(topic='org', q='Uji reaksi dengan 1 mL pereaksi Tollens menghasilkan cermin perak. Gugus fungsi apa yang terdeteksi?',
  o=['Hidrogen', 'Aldehida', 'Keton', 'Alkohol', 'Asam karboksilat'],
  e='Aldehida mereduksi ion Ag⁺ dalam pereaksi Tollens menjadi logam perak yang melapisi dinding tabung (cermin perak), sementara aldehidanya teroksidasi menjadi asam karboksilat. Keton umumnya tidak bereaksi.'),
75: dict(topic='ab', q='20 mL larutan NaOH 0,1 M direaksikan dengan 20 mL larutan CH3COOH 0,2 M (Ka = 2 × 10⁻⁵). Tentukan pH larutan setelah dicampurkan.',
  o=['5 - log 2', '5 + log 2', '9 + log 2', '9 - log 2', 'Tidak ada pilihan lain yang sesuai'], a=[0],
  e='NaOH 2 mmol bereaksi dengan CH3COOH 4 mmol, tersisa CH3COOH 2 mmol dan terbentuk CH3COONa 2 mmol. Ini buffer asam: [H⁺] = Ka × 2/2 = 2 × 10⁻⁵, jadi pH = 5 - log 2 (sekitar 4,7).',
  note='Kunci di file asli 9 - log 2 dan konstantanya ditulis Kb. Campuran ekuimolar asam asetat dan natrium asetat punya pH = pKa, sekitar 4,7, jadi kuncinya dikoreksi ke 5 - log 2.'),
71: dict(topic='fis', q='Susu dan santan termasuk sistem koloid emulsi. Pasangan fase terdispersi dan medium pendispersi pada emulsi adalah…',
  o=['Cair - cair', 'Cair - padat', 'Padat - cair', 'Gas - cair', 'Gas - padat'],
  e='Emulsi adalah cairan yang terdispersi dalam cairan lain yang tidak saling campur, misalnya tetes lemak dalam air pada susu. Padat dalam cair disebut sol, gas dalam cair disebut buih, dan gas dalam padat disebut busa padat.',
  note='Di batu hanya tercatat jawabannya ("cair cair"). Kelima pilihannya cocok dengan jenis-jenis koloid, jadi soalnya disusun ulang dari situ.'),
62: dict(topic='ling', q='Wadah penyimpanan makanan menggunakan senyawa bisfenol A (BPA). Apa dampak kesehatan jangka panjang penggunaan senyawa tersebut?',
  e='BPA adalah endocrine disruptor. Strukturnya mirip estrogen sehingga bisa menempel di reseptor estrogen, dan paparan jangka panjang dikaitkan dengan gangguan hormon serta fungsi reproduksi.'),
80: dict(topic='prot', q='Larutan asam amino yang berada pada titik isoelektriknya (pI) dialiri listrik. Asam amino tersebut akan…',
  e='Tepat di pI, asam amino berbentuk zwitterion dengan muatan bersih nol, jadi tidak tertarik ke anoda maupun katoda.'),
86: dict(topic='min', q='Mineral yang membantu perkembangan otak, tubuh, dan sistem saraf, serta berperan penting untuk kelenjar tiroid adalah…',
  e='Iodium (I) adalah bahan pembentuk hormon tiroid T3 dan T4, yang mengatur metabolisme serta tumbuh kembang otak dan saraf. Kekurangannya menyebabkan gondok, dan pada janin bisa menyebabkan kretinisme.'),
45: dict(topic='ling', q='Logam dari pabrik baterai yang mengakibatkan anak 5 tahun mengalami kerusakan otak permanen, gangguan perkembangan, IQ rendah, dan hiperaktif adalah…',
  e='Timbal (Pb) banyak dipakai di industri aki dan baterai. Anak-anak paling rentan karena penyerapannya tinggi dan sistem sarafnya masih berkembang. Paparan kronis menurunkan IQ dan menimbulkan gangguan perilaku seperti hiperaktivitas.'),
28: dict(topic='tek', q='Komponen penting pada pedometer adalah…',
  e='Pedometer menghitung langkah dari gerakan tubuh, jadi komponen intinya sensor gerak (akselerometer). Termometer dan resistor tidak bisa mendeteksi langkah.'),
51: dict(topic='ana', q='Panjang plat silika KLT adalah 13 cm, dengan batas atas dan batas bawah masing-masing 1,5 cm. Totolan bergerak sejauh 5 cm dari garis bawah. Berapakah nilai Rf-nya?',
  o=['0,50', '0,38', '0,30', '0,25', 'Tidak ada pilihan lain yang sesuai'],
  e='Jarak tempuh eluen = 13 - 1,5 - 1,5 = 10 cm. Rf = jarak totolan / jarak eluen = 5/10 = 0,50.'),
12: dict(topic='ana', q='Pada spektrofotometri, bagaimana hubungan antara transmitansi (T, dalam bentuk desimal) dan absorbansi (A)?',
  o=['A = 2 - log T', 'A = 2 + log T', 'A = 1 - log T', 'A = -log T', 'A = 1 + log T'],
  e='Absorbansi adalah negatif logaritma transmitansi: A = -log T, dengan T dalam bentuk desimal. Kalau T ditulis dalam persen, rumusnya menjadi A = 2 - log %T.'),
90: dict(topic='org', q='Reaksi yang mengganti atom H dengan atom atau gugus lain, seperti halogenasi, sulfonasi, dan nitrasi, disebut reaksi…',
  o=['Adisi', 'Substitusi', 'Eliminasi', 'Oksidasi', 'Reduksi'],
  e='Halogenasi, sulfonasi, dan nitrasi pada benzena sama-sama mengganti satu atom H dengan gugus lain tanpa merusak cincin aromatiknya, jadi termasuk substitusi. Adisi justru menambahkan atom pada ikatan rangkap.'),
19: dict(topic='saraf', q='Faktor yang paling mempengaruhi besar gaya otot adalah…',
  o=['Warna otot', 'Panjang awal serabut otot', 'Jumlah cairan intraseluler', 'Suhu lingkungan', 'Kadar hormon kortisol'],
  e='Menurut hubungan panjang-tegangan, gaya kontraksi paling besar muncul saat serabut otot berada di panjang istirahat optimal, ketika tumpang tindih aktin dan miosin paling pas. Serabut yang terlalu teregang atau terlalu pendek menghasilkan gaya lebih kecil.'),
57: dict(topic='bio', q='Polisakarida yang dimanfaatkan dalam sistem penghantaran obat adalah…',
  o=['Dekstran', 'Kitosan', 'Heparin', 'Pati', 'Glukosa'],
  a=[1, 0],
  e='Kitosan, polisakarida hasil deasetilasi kitin, bersifat biokompatibel, bisa terurai di tubuh, dan bermuatan positif sehingga mudah menempel di mukosa. Karena itu kitosan banyak dipakai sebagai pembawa obat, misalnya dalam bentuk nanopartikel.',
  note='Kunci batu: kitosan. Dekstran juga dipakai untuk penghantaran obat (lihat soal nanopartikel dekstran di bank ini), jadi dua-duanya dihitung benar.'),
30: dict(topic='ling',
  e='Cahaya dari satu sisi membuat bayangan dan kontras tidak merata, sehingga mata terus menyesuaikan diri dan persepsi kedalaman terganggu. Karena mahasiswa terus menggeser kepala dan badan mencari posisi terang, lama-lama muncul keluhan otot di leher, bahu, dan punggung.'),
31: dict(topic='org', q='Alkohol yang digunakan untuk antiseptik adalah…', o=['Isopropanol', 'Metanol', 'Etanol', 'Gliserol', 'Butanol'], a=[0, 2],
  e='Isopropanol dan etanol 70% sama-sama dipakai sebagai antiseptik kulit karena mendenaturasi protein mikroba. Metanol beracun dan tidak dipakai sebagai antiseptik.',
  note='Kunci batu: isopropanol. Etanol juga antiseptik (materi yang sama menyebut isopropanol dan etanol 70%), jadi dua-duanya dihitung benar. Pilihan "propanol" di file asli diganti gliserol, karena n-propanol juga dipakai di sebagian hand rub.'),
72: dict(topic='org', q='Asam karboksilat yang digunakan untuk senyawa obat dan kecantikan adalah…',
  e='Asam salisilat adalah bahan baku aspirin dan dipakai di produk perawatan kulit karena bersifat keratolitik, misalnya untuk jerawat dan pengelupasan kulit mati.'),
94: dict(topic='fis', q='Seorang pasien dengan kadar albumin darah yang rendah mengalami edema. Mekanisme yang paling mungkin mendasarinya adalah…',
  e='Tekanan onkotik plasma, terutama dari albumin, menahan cairan tetap di dalam pembuluh. Kalau tekanan ini turun (misalnya pada hipoalbuminemia), cairan lebih banyak keluar ke interstisial dan terjadi edema.',
  note='Skenario lengkapnya tidak tercatat di batu. Keterangan albumin rendah ditambahkan supaya soal cocok dengan kuncinya, karena tanpa itu kenaikan tekanan hidrostatik juga bisa jadi jawaban.'),
42: dict(topic='prot', q='Asam amino yang memiliki kapasitas buffer terbaik di sekitar pH 7,4 adalah…',
  e='Gugus imidazol histidin punya pKa sekitar 6,0 (di dalam protein bisa 6-7), jadi di antara pilihan yang ada hanya rantai samping histidin yang bisa menerima dan melepas H⁺ di sekitar pH netral. Itu sebabnya histidin jadi buffer terbaik di sekitar pH 7,4, contohnya residu histidin di hemoglobin.'),
35: dict(topic='org', q='Senyawa ini digunakan dalam perawatan kulit, dan pada konsentrasi tertentu dipakai seperti formalin dalam chemical peeling. Senyawa apakah itu?',
  o=['Aseton', 'Alkohol', 'Isopropil alkohol', 'Glutaraldehid', 'Kortison'], a=[3, 0],
  e='Glutaraldehid adalah dialdehida yang sekerabat dengan formalin (formaldehida). Selain sebagai desinfektan, larutannya dengan kadar tertentu dipakai secara topikal di kulit, misalnya untuk kutil dan keringat berlebih.',
  note='Kalimat soal di batu kurang lengkap. Kunci batu glutaraldehid (sekerabat formalin). Aseton juga dipakai dalam chemical peeling, untuk membersihkan minyak kulit sebelum peeling, jadi dua-duanya dihitung benar.'),
16: dict(topic='ab', q='Bagaimana hubungan SID yang meningkat terhadap [H⁺] dan [OH⁻]?',
  o=['H⁺ menurun, OH⁻ meningkat', 'H⁺ rendah, OH⁻ tinggi', 'H⁺ dan OH⁻ sama-sama tinggi', 'H⁺ dan OH⁻ sama-sama rendah', 'Tidak ada perubahan'], a=[0, 1],
  e='Dalam pendekatan Stewart, SID (strong ion difference) yang naik membuat cairan lebih basa: [H⁺] turun dan [OH⁻] naik, seperti pada alkalosis metabolik. SID yang turun menyebabkan asidosis.',
  note='Pilihan A dan B menggambarkan perubahan yang sama, jadi keduanya dihitung benar. Kunci batu: A.'),
32: dict(topic='fis', q='Gerak Brown diamati pada partikel A dan B. Partikel A lebih kecil daripada B. Bagaimana gerak partikel A?',
  o=['Lebih cepat', 'Lebih lambat', 'Tetap sama', 'Berhenti', 'Berubah arah'],
  e='Partikel yang lebih kecil massanya lebih kecil, jadi tumbukan acak molekul pelarut lebih mudah menggerakkannya. Gerak Brown partikel A lebih cepat daripada B.'),
18: dict(topic='ab', q='Ekuivalensi asam adalah banyaknya asam yang dapat bereaksi dengan 1 mol ion OH⁻. Berapa mol OH⁻ yang bereaksi dengan 1 mol H2SO4?',
  o=['3 mol OH⁻', '1/2 mol OH⁻', '4 mol OH⁻', '1 mol OH⁻', '2 mol OH⁻'], a=[4],
  e='H2SO4 asam diprotik: H2SO4 + 2OH⁻ → SO4²⁻ + 2H2O. Jadi 1 mol H2SO4 bereaksi dengan 2 mol OH⁻, atau setara 2 ekuivalen.',
  note='Kunci di file asli 1/2 mol, padahal itu jawaban untuk pertanyaan kebalikannya (berapa mol H2SO4 yang bereaksi dengan 1 mol OH⁻). Di file asli, pilihan "2 MOL OH-" juga satu-satunya yang ditulis kapital.'),
24: dict(topic='prot', q='Anemia sel sabit terjadi ketika asam amino nomor 6 pada struktur primer rantai β-globin diganti menjadi…',
  o=['Glutamat', 'Leusin', 'Valin', 'Glisin', 'Alanin'],
  e='Pada HbS, asam glutamat (bermuatan, hidrofilik) di posisi 6 rantai β-globin diganti valin (hidrofobik). Saat deoksigenasi valin ini membuat molekul hemoglobin saling menempel dan berpolimer, sehingga eritrosit berubah bentuk jadi sabit.'),
54: dict(topic='ana', q='Diketahui persamaan kurva baku y = 0,001x - 0,32. Nilai absorbansi sampel sebesar 0,15. Nilai C terukurnya adalah…',
  e='Masukkan absorbansi sebagai y: 0,15 = 0,001x - 0,32, jadi 0,001x = 0,47 dan x = 470.'),
65: dict(topic='saraf', q='Contoh gerakan isometrik dalam kehidupan sehari-hari adalah…',
  e='Kontraksi isometrik menghasilkan tegangan tanpa perubahan panjang otot atau gerakan sendi, seperti saat menahan posisi push-up atau plank. Mengangkat buku, berjalan, melompat, dan melempar melibatkan kontraksi isotonik.'),
69: dict(topic='ana', q='Kadar alkohol dalam darah (Blood Alcohol Content, BAC) diukur dari etanol, yang mudah menguap pada suhu ruang. Kromatografi apa yang menjadi baku emas untuk kasus forensik ini?',
  o=['KLT', 'HPLC', 'Kromatografi gas', 'Spektrofotometri', 'Elektroforesis'],
  e='Etanol mudah menguap, jadi paling cocok dianalisis dengan kromatografi gas (biasanya teknik headspace). Metode ini jadi standar pemeriksaan kadar alkohol darah untuk keperluan forensik.'),
89: dict(topic='saraf', q='Saat berjalan, otot betis berfungsi untuk…',
  o=['Menggerakkan lutut', 'Mengangkat tumit', 'Menggoyangkan pinggul', 'Fleksi siku', 'Ekstensi pergelangan tangan'],
  e='Otot betis (gastroknemius dan soleus) melakukan plantarfleksi, yaitu mengangkat tumit saat kaki mendorong badan ke depan ketika berjalan.'),
13: dict(topic='ab', q='Larutan CH3COOH memiliki pH 3. Jika larutan tersebut diencerkan dengan akuades hingga 100 kali lipat, berapa pH akhir larutan?', a=[0],
  e='CH3COOH asam lemah, jadi [H⁺] = √(Ka × M). Pengenceran 100 kali menurunkan M 100 kali, tapi [H⁺] hanya turun √100 = 10 kali: dari 10⁻³ menjadi 10⁻⁴. pH akhirnya 4.',
  note='Kunci di file asli 5. Angka itu berlaku untuk asam kuat, sedangkan asam asetat asam lemah, jadi kuncinya dikoreksi ke 4.'),
6: dict(topic='min', q='Mineral yang berfungsi untuk antioksidan glutation serta jaringan ikat (kuku, kulit, rambut) adalah…',
  e='Sulfur (S) terdapat di asam amino sistein dan metionin, menjadi bagian antioksidan glutation, dan membentuk ikatan disulfida di keratin kuku, kulit, dan rambut.'),
38: dict(topic='ab',
  o=['Kertas lakmus merah berubah menjadi biru, kertas lakmus biru tetap biru', 'Kertas lakmus merah tetap merah, kertas lakmus biru menjadi merah', 'Tidak terjadi perubahan pada keduanya', 'Kertas lakmus merah berubah ungu, kertas lakmus biru berubah hijau', 'Tidak ada pilihan lain yang sesuai'],
  e='Urin dengan pH 5,0 bersifat asam. Dalam suasana asam, lakmus merah tetap merah dan lakmus biru berubah menjadi merah.'),
29: dict(topic='prot', q='Alzheimer disebabkan oleh…',
  e='Pada Alzheimer, protein β-amiloid dan tau salah melipat (misfolding) lalu menggumpal menjadi plak amiloid dan neurofibrillary tangle yang merusak neuron.'),
36: dict(topic='fis', q='Seseorang menuang tinta ke dalam gelas berisi air. Tinta menyebar dan tidak pernah berkumpul kembali. Prinsip termodinamika yang digambarkan peristiwa ini adalah…',
  o=['Difusi', 'Hukum I Termodinamika', 'Hukum III Termodinamika', 'Hukum II Termodinamika', 'Homeostasis'], a=[3],
  e='Proses spontan selalu bergerak ke arah ketidakteraturan (entropi) yang lebih besar dan tidak bisa balik sendiri. Itu isi Hukum II Termodinamika. Tinta memang menyebar lewat difusi, tapi yang ditanyakan prinsip di balik arah prosesnya.',
  note='Kunci di file asli "Hukum I", padahal Hukum I hanya soal kekekalan energi. Kuncinya dikoreksi ke Hukum II.'),
92: dict(topic='fis', q='Seseorang mengalami demam. Tubuhnya melakukan vasodilatasi kulit dan mengeluarkan keringat untuk menurunkan suhu tubuh. Hal ini sesuai dengan prinsip…',
  o=['Homeostasis', 'Difusi', 'Osmosis', 'Denaturasi', 'Filtrasi'],
  e='Vasodilatasi kulit dan berkeringat adalah umpan balik negatif untuk membuang panas, supaya suhu tubuh kembali ke nilai normal. Menjaga kondisi internal tetap stabil seperti ini disebut homeostasis.'),
34: dict(topic='ab', q='Apoteker meracik obat tetes mata antibiotik. Larutannya harus isotonis agar tidak menimbulkan iritasi. Apa yang harus dilakukan?',
  o=['Menghitung berat molekul larutan', 'Menghitung ekivalensi NaCl (nilai E)', 'Mengurangi volume air', 'Menambahkan glukosa', 'Menggunakan larutan hipertonik'],
  e='Supaya isotonis, jumlah NaCl yang perlu ditambahkan dihitung dengan metode ekivalensi NaCl (nilai E): jumlah NaCl yang efek osmotiknya setara dengan 1 g obat. Larutan hipertonik justru bikin iritasi.'),
97: dict(topic='ana', q='Spektrofotometer digunakan untuk mendeteksi kadar kreatinin dan ureum untuk menilai fungsi ginjal. Manfaat ini termasuk bidang apa?',
  e='Pengukuran kadar zat dalam darah seperti ureum dan kreatinin untuk menilai fungsi ginjal termasuk pemeriksaan kimia klinik (kimia medik), dan sebagian besar dikerjakan dengan spektrofotometer.',
  note='Di file asli tertulis "kadar blablabla dan ureum". Diisi kreatinin, pasangan ureum yang lazim untuk fungsi ginjal.'),
88: dict(topic='ling', q='Pekerja tambang mengalami sesak napas, mual, dan pusing, padahal PO2 darahnya normal. Penyebab yang paling mungkin adalah…',
  e='CO berikatan dengan hemoglobin sekitar 200-250 kali lebih kuat daripada O2 dan membentuk karboksihemoglobin. O2 terlarut (PO2) tetap normal, tapi kemampuan Hb mengangkut O2 turun, jadi jaringan tetap kekurangan oksigen.'),
49: dict(topic='ab', q='Seseorang masuk IGD lalu diinfus aquades steril melalui vena dalam jumlah banyak. Apa dampaknya bagi sel eritrosit?',
  o=['Tidak ada hubungan', 'Selnya menebal', 'Terjadi hemodialisis', 'Terjadi krenasi', 'Terjadi hemolisis'], a=[4],
  e='Aquades jauh lebih hipotonis daripada plasma. Air masuk ke eritrosit secara osmosis sampai sel membengkak dan pecah (hemolisis). Krenasi atau sel mengerut terjadi di larutan hipertonis.',
  note='Kunci di file asli krenasi. Dikoreksi ke hemolisis, sesuai soal hipotonis lain di bank ini.'),
46: dict(topic='ling',
  e='Kontras tajam antara meja yang terang dan sekeliling yang gelap membuat pupil terus mengecil dan membesar tiap kali pandangan berpindah. Mata cepat lelah, fokus jadi sulit, dan posisi tubuh yang kaku lama-lama membuat leher kaku.'),
78: dict(topic='fis', q='Semakin banyak zat terlarut dalam suatu larutan, bagaimana kecepatan gerak Brown partikelnya?',
  o=['Lebih cepat', 'Lebih lambat', 'Tetap', 'Berhenti', 'Tidak teratur'],
  e='Makin banyak zat terlarut, larutan makin kental dan partikel makin sering bertumbukan, jadi gerak Brown partikelnya makin lambat.'),
64: dict(topic='prot', q='Asam amino pembentuk rantai awal yang dikode oleh AUG adalah…', o=['Serin', 'Alanin', 'Glutamin', 'Metionin', 'Valin'],
  e='AUG adalah kodon awal (start codon) sekaligus kode metionin, jadi sintesis polipeptida selalu dimulai dari metionin (pada bakteri N-formilmetionin).'),
53: dict(topic='prot', q='Seseorang yang kurang tidur pergi ke dokter dan diberi asam amino prekursor serotonin dan melatonin, yaitu…',
  e='Triptofan diubah menjadi 5-hidroksitriptofan lalu serotonin. Di kelenjar pineal, serotonin diubah lagi menjadi melatonin yang mengatur siklus tidur.'),
39: dict(topic='org', q='Gas golongan hidrokarbon ini pada tahun 1920-an banyak digunakan sebagai anestesi inhalasi yang dikombinasikan dengan oksigen murni. Gas apakah itu?',
  e='Pada 1920-an etuna (asetilena, C2H2) dan etilena sama-sama pernah dipakai sebagai anestesi inhalasi yang dicampur oksigen. Karena etilena dan etena adalah dua nama untuk senyawa yang sama (C2H4), pilihan itu tidak mungkin jadi satu-satunya jawaban, sehingga kunci batu memilih etuna.',
  note='Kunci mengikuti batu.'),
61: dict(topic='bio', q='Amilase memecah pati menjadi produk antara, yaitu…',
  e='Amilase dari ludah dan pankreas memotong ikatan α-1,4 glikosidik pati menjadi maltosa, maltotriosa, dan dekstrin. Maltosa lalu dipecah maltase menjadi glukosa.'),
9: dict(topic='ab', q='Seseorang mengalami pneumonia sehingga darahnya menjadi asidosis respiratorik. Perubahan primer yang terjadi di dalam darah adalah…',
  o=['PCO2 meningkat', 'PCO2 menurun', 'HCO3⁻ meningkat', 'HCO3⁻ menurun', 'Kadar PCO2 tetap'],
  e='Pada pneumonia, ventilasi alveolus terganggu sehingga CO2 tertahan dan PCO2 naik. Kesetimbangan CO2 + H2O ⇌ H2CO3 ⇌ H⁺ + HCO3⁻ bergeser ke kanan, H⁺ bertambah, dan pH turun.'),
82: dict(topic='min', q='Mineral untuk pembentukan darah adalah…',
  e='Besi (Fe) adalah atom pusat heme pada hemoglobin, jadi mutlak dibutuhkan untuk membentuk eritrosit. Kekurangannya menyebabkan anemia defisiensi besi.'),
81: dict(topic='min', q='Mineral untuk jantung dan limpa adalah…',
  e='Selenium (Se) adalah komponen enzim antioksidan glutation peroksidase. Kekurangannya dikaitkan dengan kardiomiopati (penyakit Keshan) dan menurunnya fungsi sistem imun.'),
20: dict(topic='ana', q='Rumus perhitungan kadar asam salisilat (sesuai penuntun praktikum) adalah…',
  e='Rumus ini berasal dari penuntun praktikum penetapan kadar asam salisilat, dengan A1 dan A2 sebagai nilai absorbansi hasil pengukuran. Yang perlu dihafal: 3,58 dikalikan A2, dikurangi 3,49 dikalikan A1.'),
91: dict(topic='org', q='Reduksi Cu²⁺ menjadi Cu⁺ menghasilkan…',
  o=['Endapan merah bata', 'Endapan putih', 'Endapan hitam', 'Larutan biru jernih', 'Gas'],
  e='Pada uji Benedict atau Fehling, gula pereduksi mereduksi Cu²⁺ yang berwarna biru menjadi Cu⁺, yang mengendap sebagai Cu2O berwarna merah bata.'),
79: dict(topic='fis', q='Tekanan total suatu campuran gas yang tidak bereaksi secara kimia sama dengan jumlah tekanan parsial dari masing-masing gas penyusunnya. Pernyataan ini adalah…',
  o=['Hukum tekanan parsial Dalton', 'Kesetimbangan Donnan', 'Hukum Boyle', 'Hukum Charles', 'Hukum Graham'],
  e='Hukum Dalton menyatakan tekanan total campuran gas sama dengan jumlah tekanan parsial tiap gas. Di fisiologi, hukum ini dipakai untuk menghitung PO2 dan PCO2 di udara dan alveolus.'),
95: dict(topic='min',
  e='Kalium (K⁺) menjaga potensial membran otot dan saraf. Hipokalemia menyebabkan lemas, kram, konstipasi karena otot polos usus melemah, sampai kelumpuhan. Kelebihan kalium berbahaya bagi irama jantung dan erat kaitannya dengan gangguan ginjal, karena ginjal adalah jalur utama pembuangan kalium.'),
2: dict(topic='ling', q='Berapa Nilai Ambang Batas (NAB) kebisingan menurut Permenakertrans No. 13 Tahun 2011 (dalam dBA)?',
  e='Permenakertrans No. 13 Tahun 2011 menetapkan NAB kebisingan 85 dBA untuk paparan 8 jam per hari atau 40 jam per minggu.'),
}

# Duplicates of cleaner items in the 200 file (kept there): A3=B181, A4=B184, A33=B136, A76=B183, A96=B069
DROP_A = {3, 4, 33, 76, 96}
